### ISSUE TITLE
cabal.exe: There is no package named 'safe-tidal'. Windows 10

### ISSUE THREAD

**Issue by junekuhn** [jwaldmann/safe-tidal-cli#15]
I get the following error when trying to install.  I currently have tidal 1.7.2 installed through cabal.

PS C:\WINDOWS\system32> cabal install safe-tidal
cabal.exe: There is no package named 'safe-tidal'.
You may need to run 'cabal update' to get the latest list of available
packages.

**Comment by jwaldmann** [comment]
yes, as safe-tidal is not released on hackage. you should be able to build from source, like this:
```
git clone https://github.com/jwaldmann/safe-tidal-cli
cd safe-tidal-cli/
cabal install
```

**Comment by junekuhn** [comment]
Sorry, that wasn't obvious from the README.  I'm fairly new to Haskell.
